services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9696:9696
    volumes:
      - /home/brad/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=WIREGUARD_PRIVATE_KEY
      - WIREGUARD_PRESHARED_KEY=WIREGUARD_PRESHARED_KEY
      - WIREGUARD_ADDRESSES=10.178.230.39/32
    restart: unless-stopped
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/brad/docker/prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /home/brad/docker/sabnzbd/config:/config
      - /mnt/data:/data
      - /usenet:/usenet
    
    ports:
      - 8080:8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/brad/docker/sonarr:/config
      - /mnt/data:/data
      - /usenet:/usenet
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/brad/docker/radarr:/config
      - /mnt/data:/data
      - /usenet:/usenet
    ports:
      - 7878:7878
    restart: unless-stopped
