services:
    server:
        container_name: vaultwarden
        volumes:
            - '/home/brad/docker/vaultwarden:/data/'
        environment:
            - SIGNUPS_ALLOWED=true
            - ADMIN_TOKEN=63KjVjuJPfnZWHivaZJ548P8vbpDWE+Nxvdoxhg96RydMl9bzB8gUMW8muCpxzjI
        ports:
            - '8888:80'
        networks:
          - proxy
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vaultwarden.entrypoints=http"
        - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.half.black`)"
        - "traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.vaultwarden.middlewares=vaultwarden-https-redirect"
        - "traefik.http.routers.vaultwarden-secure.entrypoints=https"
        - "traefik.http.routers.vaultwarden-secure.rule=Host(`vaultwarden.half.black`)"
        - "traefik.http.routers.vaultwarden-secure.tls=true"
        - "traefik.http.services.vaultwarden-websecure.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
        image: 'vaultwarden/server:latest'

networks:
  proxy:
    external: true